export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CARS_SUCCESS ="GET_CARS_SUCCESS";
export const ADD_TO_CAR_PAGE ="ADD_TO_CAR_PAGE";
export const REMOVE_FROM_CAR_PAGE ="REMOVE_FROM_CAR_PAGE";